import tryToFindContentDetailsFromFilePath from "./try-to-find-content-details-from-file-path"

describe(`@woobly/build-tool-helpers`, () => {
  describe(`tryToFindContentDetailsFromFilePath`, () => {
    function converts(
      description: string,
      filePath: string,
      typeScriptIdentifier: string,
      fileExtension: string,
    ): void {
      describe(description, () => {
        let result: null | {
          readonly typeScriptIdentifier: string
          readonly fileExtension: string
        }

        beforeAll(() => result = tryToFindContentDetailsFromFilePath(filePath))

        it(
          `is accepted as it is convertible to a TypeScript identifier`,
          () => expect(result).not.toBeNull()
        )

        it(
          `includes the expected TypeScript identifier`,
          () => expect(result && result.typeScriptIdentifier).toEqual(typeScriptIdentifier)
        )

        it(
          `includes the expected file extension`,
          () => expect(result && result.fileExtension).toEqual(fileExtension)
        )

        it(
          `includes no further information`,
          () => expect(Object.keys(result || {}).length).toEqual(2)
        )
      })
    }

    function rejects(
      description: string,
      filePath: string,
    ): void {
      describe(description, () => {
        it(
          `is rejected as it is not convertible to a TypeScript identifier`,
          () => expect(tryToFindContentDetailsFromFilePath(filePath)).toBeNull()
        )
      })
    }

    converts(`one segment one extension forward slashes`, `src/te5t.ext3nsion`, `te5t`, `ext3nsion`)
    converts(`one segment one extension back slashes`, `src\\te5t.ext3nsion`, `te5t`, `ext3nsion`)
    converts(`two segments one extension forward slashes`, `src/te5t-segment.ext3nsion`, `te5tSegment`, `ext3nsion`)
    converts(`two segments one extension back slashes`, `src\\te5t-segment.ext3nsion`, `te5tSegment`, `ext3nsion`)
    converts(`three segments one extension forward slashes`, `src/te5t-segment-list.ext3nsion`, `te5tSegmentList`, `ext3nsion`)
    converts(`three segments one extension back slashes`, `src\\te5t-segment-list.ext3nsion`, `te5tSegmentList`, `ext3nsion`)
    converts(`one, one segment one extension forward slashes`, `src/te5t/d1rectory.ext3nsion`, `te5tD1rectory`, `ext3nsion`)
    converts(`one, one segment one extension back slashes`, `src\\te5t\\d1rectory.ext3nsion`, `te5tD1rectory`, `ext3nsion`)
    converts(`one, two segments one extension forward slashes`, `src/te5t/sub-d1rectory.ext3nsion`, `te5tSubD1rectory`, `ext3nsion`)
    converts(`one, two segments one extension back slashes`, `src\\te5t\\sub-d1rectory.ext3nsion`, `te5tSubD1rectory`, `ext3nsion`)
    converts(`one, three segments one extension forward slashes`, `src/te5t/sub-d1rectory-name.ext3nsion`, `te5tSubD1rectoryName`, `ext3nsion`)
    converts(`one, three segments one extension back slashes`, `src\\te5t\\sub-d1rectory-name.ext3nsion`, `te5tSubD1rectoryName`, `ext3nsion`)
    converts(`two, one segment one extension forward slashes`, `src/te5t-segment/d1rectory.ext3nsion`, `te5tSegmentD1rectory`, `ext3nsion`)
    converts(`two, one segment one extension back slashes`, `src\\te5t-segment\\d1rectory.ext3nsion`, `te5tSegmentD1rectory`, `ext3nsion`)
    converts(`two, two segments one extension forward slashes`, `src/te5t-segment/sub-d1rectory.ext3nsion`, `te5tSegmentSubD1rectory`, `ext3nsion`)
    converts(`two, two segments one extension back slashes`, `src\\te5t-segment\\sub-d1rectory.ext3nsion`, `te5tSegmentSubD1rectory`, `ext3nsion`)
    converts(`two, three segments one extension forward slashes`, `src/te5t-segment/sub-d1rectory-name.ext3nsion`, `te5tSegmentSubD1rectoryName`, `ext3nsion`)
    converts(`two, three segments one extension back slashes`, `src\\te5t-segment\\sub-d1rectory-name.ext3nsion`, `te5tSegmentSubD1rectoryName`, `ext3nsion`)
    converts(`three, one segment one extension forward slashes`, `src/te5t-segment-list/d1rectory.ext3nsion`, `te5tSegmentListD1rectory`, `ext3nsion`)
    converts(`three, one segment one extension back slashes`, `src\\te5t-segment-list\\d1rectory.ext3nsion`, `te5tSegmentListD1rectory`, `ext3nsion`)
    converts(`three, two segments one extension forward slashes`, `src/te5t-segment-list/sub-d1rectory.ext3nsion`, `te5tSegmentListSubD1rectory`, `ext3nsion`)
    converts(`three, two segments one extension back slashes`, `src\\te5t-segment-list\\sub-d1rectory.ext3nsion`, `te5tSegmentListSubD1rectory`, `ext3nsion`)
    converts(`three, three segments one extension forward slashes`, `src/te5t-segment-list/sub-d1rectory-name.ext3nsion`, `te5tSegmentListSubD1rectoryName`, `ext3nsion`)
    converts(`three, three segments one extension back slashes`, `src\\te5t-segment-list\\sub-d1rectory-name.ext3nsion`, `te5tSegmentListSubD1rectoryName`, `ext3nsion`)
    converts(`one, one segment one extension forward slashes`, `src/parent/te5t.ext3nsion`, `parentTe5t`, `ext3nsion`)
    converts(`one, one segment one extension back slashes`, `src\\parent\\te5t.ext3nsion`, `parentTe5t`, `ext3nsion`)
    converts(`one, two segments one extension forward slashes`, `src/parent/te5t-segment.ext3nsion`, `parentTe5tSegment`, `ext3nsion`)
    converts(`one, two segments one extension back slashes`, `src\\parent\\te5t-segment.ext3nsion`, `parentTe5tSegment`, `ext3nsion`)
    converts(`one, three segments one extension forward slashes`, `src/parent/te5t-segment-list.ext3nsion`, `parentTe5tSegmentList`, `ext3nsion`)
    converts(`one, three segments one extension back slashes`, `src\\parent\\te5t-segment-list.ext3nsion`, `parentTe5tSegmentList`, `ext3nsion`)
    converts(`one, one, one segment one extension forward slashes`, `src/parent/te5t/d1rectory.ext3nsion`, `parentTe5tD1rectory`, `ext3nsion`)
    converts(`one, one, one segment one extension back slashes`, `src\\parent\\te5t\\d1rectory.ext3nsion`, `parentTe5tD1rectory`, `ext3nsion`)
    converts(`one, one, two segments one extension forward slashes`, `src/parent/te5t/sub-d1rectory.ext3nsion`, `parentTe5tSubD1rectory`, `ext3nsion`)
    converts(`one, one, two segments one extension back slashes`, `src\\parent\\te5t\\sub-d1rectory.ext3nsion`, `parentTe5tSubD1rectory`, `ext3nsion`)
    converts(`one, one, three segments one extension forward slashes`, `src/parent/te5t/sub-d1rectory-name.ext3nsion`, `parentTe5tSubD1rectoryName`, `ext3nsion`)
    converts(`one, one, three segments one extension back slashes`, `src\\parent\\te5t\\sub-d1rectory-name.ext3nsion`, `parentTe5tSubD1rectoryName`, `ext3nsion`)
    converts(`one, two, one segment one extension forward slashes`, `src/parent/te5t-segment/d1rectory.ext3nsion`, `parentTe5tSegmentD1rectory`, `ext3nsion`)
    converts(`one, two, one segment one extension back slashes`, `src\\parent\\te5t-segment\\d1rectory.ext3nsion`, `parentTe5tSegmentD1rectory`, `ext3nsion`)
    converts(`one, two, two segments one extension forward slashes`, `src/parent/te5t-segment/sub-d1rectory.ext3nsion`, `parentTe5tSegmentSubD1rectory`, `ext3nsion`)
    converts(`one, two, two segments one extension back slashes`, `src\\parent\\te5t-segment\\sub-d1rectory.ext3nsion`, `parentTe5tSegmentSubD1rectory`, `ext3nsion`)
    converts(`one, two, three segments one extension forward slashes`, `src/parent/te5t-segment/sub-d1rectory-name.ext3nsion`, `parentTe5tSegmentSubD1rectoryName`, `ext3nsion`)
    converts(`one, two, three segments one extension back slashes`, `src\\parent\\te5t-segment\\sub-d1rectory-name.ext3nsion`, `parentTe5tSegmentSubD1rectoryName`, `ext3nsion`)
    converts(`one, three, one segment one extension forward slashes`, `src/parent/te5t-segment-list/d1rectory.ext3nsion`, `parentTe5tSegmentListD1rectory`, `ext3nsion`)
    converts(`one, three, one segment one extension back slashes`, `src\\parent\\te5t-segment-list\\d1rectory.ext3nsion`, `parentTe5tSegmentListD1rectory`, `ext3nsion`)
    converts(`one, three, two segments one extension forward slashes`, `src/parent/te5t-segment-list/sub-d1rectory.ext3nsion`, `parentTe5tSegmentListSubD1rectory`, `ext3nsion`)
    converts(`one, three, two segments one extension back slashes`, `src\\parent\\te5t-segment-list\\sub-d1rectory.ext3nsion`, `parentTe5tSegmentListSubD1rectory`, `ext3nsion`)
    converts(`one, three, three segments one extension forward slashes`, `src/parent/te5t-segment-list/sub-d1rectory-name.ext3nsion`, `parentTe5tSegmentListSubD1rectoryName`, `ext3nsion`)
    converts(`one, three, three segments one extension back slashes`, `src\\parent\\te5t-segment-list\\sub-d1rectory-name.ext3nsion`, `parentTe5tSegmentListSubD1rectoryName`, `ext3nsion`)
    converts(`two, one segment one extension forward slashes`, `src/parent-folder/te5t.ext3nsion`, `parentFolderTe5t`, `ext3nsion`)
    converts(`two, one segment one extension back slashes`, `src\\parent-folder\\te5t.ext3nsion`, `parentFolderTe5t`, `ext3nsion`)
    converts(`two, two segments one extension forward slashes`, `src/parent-folder/te5t-segment.ext3nsion`, `parentFolderTe5tSegment`, `ext3nsion`)
    converts(`two, two segments one extension back slashes`, `src\\parent-folder\\te5t-segment.ext3nsion`, `parentFolderTe5tSegment`, `ext3nsion`)
    converts(`two, three segments one extension forward slashes`, `src/parent-folder/te5t-segment-list.ext3nsion`, `parentFolderTe5tSegmentList`, `ext3nsion`)
    converts(`two, three segments one extension back slashes`, `src\\parent-folder\\te5t-segment-list.ext3nsion`, `parentFolderTe5tSegmentList`, `ext3nsion`)
    converts(`two, one, one segment one extension forward slashes`, `src/parent-folder/te5t/d1rectory.ext3nsion`, `parentFolderTe5tD1rectory`, `ext3nsion`)
    converts(`two, one, one segment one extension back slashes`, `src\\parent-folder\\te5t\\d1rectory.ext3nsion`, `parentFolderTe5tD1rectory`, `ext3nsion`)
    converts(`two, one, two segments one extension forward slashes`, `src/parent-folder/te5t/sub-d1rectory.ext3nsion`, `parentFolderTe5tSubD1rectory`, `ext3nsion`)
    converts(`two, one, two segments one extension back slashes`, `src\\parent-folder\\te5t\\sub-d1rectory.ext3nsion`, `parentFolderTe5tSubD1rectory`, `ext3nsion`)
    converts(`two, one, three segments one extension forward slashes`, `src/parent-folder/te5t/sub-d1rectory-name.ext3nsion`, `parentFolderTe5tSubD1rectoryName`, `ext3nsion`)
    converts(`two, one, three segments one extension back slashes`, `src\\parent-folder\\te5t\\sub-d1rectory-name.ext3nsion`, `parentFolderTe5tSubD1rectoryName`, `ext3nsion`)
    converts(`two, two, one segment one extension forward slashes`, `src/parent-folder/te5t-segment/d1rectory.ext3nsion`, `parentFolderTe5tSegmentD1rectory`, `ext3nsion`)
    converts(`two, two, one segment one extension back slashes`, `src\\parent-folder\\te5t-segment\\d1rectory.ext3nsion`, `parentFolderTe5tSegmentD1rectory`, `ext3nsion`)
    converts(`two, two, two segments one extension forward slashes`, `src/parent-folder/te5t-segment/sub-d1rectory.ext3nsion`, `parentFolderTe5tSegmentSubD1rectory`, `ext3nsion`)
    converts(`two, two, two segments one extension back slashes`, `src\\parent-folder\\te5t-segment\\sub-d1rectory.ext3nsion`, `parentFolderTe5tSegmentSubD1rectory`, `ext3nsion`)
    converts(`two, two, three segments one extension forward slashes`, `src/parent-folder/te5t-segment/sub-d1rectory-name.ext3nsion`, `parentFolderTe5tSegmentSubD1rectoryName`, `ext3nsion`)
    converts(`two, two, three segments one extension back slashes`, `src\\parent-folder\\te5t-segment\\sub-d1rectory-name.ext3nsion`, `parentFolderTe5tSegmentSubD1rectoryName`, `ext3nsion`)
    converts(`two, three, one segment one extension forward slashes`, `src/parent-folder/te5t-segment-list/d1rectory.ext3nsion`, `parentFolderTe5tSegmentListD1rectory`, `ext3nsion`)
    converts(`two, three, one segment one extension back slashes`, `src\\parent-folder\\te5t-segment-list\\d1rectory.ext3nsion`, `parentFolderTe5tSegmentListD1rectory`, `ext3nsion`)
    converts(`two, three, two segments one extension forward slashes`, `src/parent-folder/te5t-segment-list/sub-d1rectory.ext3nsion`, `parentFolderTe5tSegmentListSubD1rectory`, `ext3nsion`)
    converts(`two, three, two segments one extension back slashes`, `src\\parent-folder\\te5t-segment-list\\sub-d1rectory.ext3nsion`, `parentFolderTe5tSegmentListSubD1rectory`, `ext3nsion`)
    converts(`two, three, three segments one extension forward slashes`, `src/parent-folder/te5t-segment-list/sub-d1rectory-name.ext3nsion`, `parentFolderTe5tSegmentListSubD1rectoryName`, `ext3nsion`)
    converts(`two, three, three segments one extension back slashes`, `src\\parent-folder\\te5t-segment-list\\sub-d1rectory-name.ext3nsion`, `parentFolderTe5tSegmentListSubD1rectoryName`, `ext3nsion`)
    converts(`three, one segment one extension forward slashes`, `src/parent-folder-n0menclature/te5t.ext3nsion`, `parentFolderN0menclatureTe5t`, `ext3nsion`)
    converts(`three, one segment one extension back slashes`, `src\\parent-folder-n0menclature\\te5t.ext3nsion`, `parentFolderN0menclatureTe5t`, `ext3nsion`)
    converts(`three, two segments one extension forward slashes`, `src/parent-folder-n0menclature/te5t-segment.ext3nsion`, `parentFolderN0menclatureTe5tSegment`, `ext3nsion`)
    converts(`three, two segments one extension back slashes`, `src\\parent-folder-n0menclature\\te5t-segment.ext3nsion`, `parentFolderN0menclatureTe5tSegment`, `ext3nsion`)
    converts(`three, three segments one extension forward slashes`, `src/parent-folder-n0menclature/te5t-segment-list.ext3nsion`, `parentFolderN0menclatureTe5tSegmentList`, `ext3nsion`)
    converts(`three, three segments one extension back slashes`, `src\\parent-folder-n0menclature\\te5t-segment-list.ext3nsion`, `parentFolderN0menclatureTe5tSegmentList`, `ext3nsion`)
    converts(`three, one, one segment one extension forward slashes`, `src/parent-folder-n0menclature/te5t/d1rectory.ext3nsion`, `parentFolderN0menclatureTe5tD1rectory`, `ext3nsion`)
    converts(`three, one, one segment one extension back slashes`, `src\\parent-folder-n0menclature\\te5t\\d1rectory.ext3nsion`, `parentFolderN0menclatureTe5tD1rectory`, `ext3nsion`)
    converts(`three, one, two segments one extension forward slashes`, `src/parent-folder-n0menclature/te5t/sub-d1rectory.ext3nsion`, `parentFolderN0menclatureTe5tSubD1rectory`, `ext3nsion`)
    converts(`three, one, two segments one extension back slashes`, `src\\parent-folder-n0menclature\\te5t\\sub-d1rectory.ext3nsion`, `parentFolderN0menclatureTe5tSubD1rectory`, `ext3nsion`)
    converts(`three, one, three segments one extension forward slashes`, `src/parent-folder-n0menclature/te5t/sub-d1rectory-name.ext3nsion`, `parentFolderN0menclatureTe5tSubD1rectoryName`, `ext3nsion`)
    converts(`three, one, three segments one extension back slashes`, `src\\parent-folder-n0menclature\\te5t\\sub-d1rectory-name.ext3nsion`, `parentFolderN0menclatureTe5tSubD1rectoryName`, `ext3nsion`)
    converts(`three, two, one segment one extension forward slashes`, `src/parent-folder-n0menclature/te5t-segment/d1rectory.ext3nsion`, `parentFolderN0menclatureTe5tSegmentD1rectory`, `ext3nsion`)
    converts(`three, two, one segment one extension back slashes`, `src\\parent-folder-n0menclature\\te5t-segment\\d1rectory.ext3nsion`, `parentFolderN0menclatureTe5tSegmentD1rectory`, `ext3nsion`)
    converts(`three, two, two segments one extension forward slashes`, `src/parent-folder-n0menclature/te5t-segment/sub-d1rectory.ext3nsion`, `parentFolderN0menclatureTe5tSegmentSubD1rectory`, `ext3nsion`)
    converts(`three, two, two segments one extension back slashes`, `src\\parent-folder-n0menclature\\te5t-segment\\sub-d1rectory.ext3nsion`, `parentFolderN0menclatureTe5tSegmentSubD1rectory`, `ext3nsion`)
    converts(`three, two, three segments one extension forward slashes`, `src/parent-folder-n0menclature/te5t-segment/sub-d1rectory-name.ext3nsion`, `parentFolderN0menclatureTe5tSegmentSubD1rectoryName`, `ext3nsion`)
    converts(`three, two, three segments one extension back slashes`, `src\\parent-folder-n0menclature\\te5t-segment\\sub-d1rectory-name.ext3nsion`, `parentFolderN0menclatureTe5tSegmentSubD1rectoryName`, `ext3nsion`)
    converts(`three, three, one segment one extension forward slashes`, `src/parent-folder-n0menclature/te5t-segment-list/d1rectory.ext3nsion`, `parentFolderN0menclatureTe5tSegmentListD1rectory`, `ext3nsion`)
    converts(`three, three, one segment one extension back slashes`, `src\\parent-folder-n0menclature\\te5t-segment-list\\d1rectory.ext3nsion`, `parentFolderN0menclatureTe5tSegmentListD1rectory`, `ext3nsion`)
    converts(`three, three, two segments one extension forward slashes`, `src/parent-folder-n0menclature/te5t-segment-list/sub-d1rectory.ext3nsion`, `parentFolderN0menclatureTe5tSegmentListSubD1rectory`, `ext3nsion`)
    converts(`three, three, two segments one extension back slashes`, `src\\parent-folder-n0menclature\\te5t-segment-list\\sub-d1rectory.ext3nsion`, `parentFolderN0menclatureTe5tSegmentListSubD1rectory`, `ext3nsion`)
    converts(`three, three, three segments one extension forward slashes`, `src/parent-folder-n0menclature/te5t-segment-list/sub-d1rectory-name.ext3nsion`, `parentFolderN0menclatureTe5tSegmentListSubD1rectoryName`, `ext3nsion`)
    converts(`three, three, three segments one extension back slashes`, `src\\parent-folder-n0menclature\\te5t-segment-list\\sub-d1rectory-name.ext3nsion`, `parentFolderN0menclatureTe5tSegmentListSubD1rectoryName`, `ext3nsion`)
    converts(`one segment two extensions forward slashes`, `src/te5t.ext3nsion-list`, `te5t`, `ext3nsion-list`)
    converts(`one segment two extensions back slashes`, `src\\te5t.ext3nsion-list`, `te5t`, `ext3nsion-list`)
    converts(`two segments two extensions forward slashes`, `src/te5t-segment.ext3nsion-list`, `te5tSegment`, `ext3nsion-list`)
    converts(`two segments two extensions back slashes`, `src\\te5t-segment.ext3nsion-list`, `te5tSegment`, `ext3nsion-list`)
    converts(`three segments two extensions forward slashes`, `src/te5t-segment-list.ext3nsion-list`, `te5tSegmentList`, `ext3nsion-list`)
    converts(`three segments two extensions back slashes`, `src\\te5t-segment-list.ext3nsion-list`, `te5tSegmentList`, `ext3nsion-list`)
    converts(`one, one segment two extensions forward slashes`, `src/te5t/d1rectory.ext3nsion-list`, `te5tD1rectory`, `ext3nsion-list`)
    converts(`one, one segment two extensions back slashes`, `src\\te5t\\d1rectory.ext3nsion-list`, `te5tD1rectory`, `ext3nsion-list`)
    converts(`one, two segments two extensions forward slashes`, `src/te5t/sub-d1rectory.ext3nsion-list`, `te5tSubD1rectory`, `ext3nsion-list`)
    converts(`one, two segments two extensions back slashes`, `src\\te5t\\sub-d1rectory.ext3nsion-list`, `te5tSubD1rectory`, `ext3nsion-list`)
    converts(`one, three segments two extensions forward slashes`, `src/te5t/sub-d1rectory-name.ext3nsion-list`, `te5tSubD1rectoryName`, `ext3nsion-list`)
    converts(`one, three segments two extensions back slashes`, `src\\te5t\\sub-d1rectory-name.ext3nsion-list`, `te5tSubD1rectoryName`, `ext3nsion-list`)
    converts(`two, one segment two extensions forward slashes`, `src/te5t-segment/d1rectory.ext3nsion-list`, `te5tSegmentD1rectory`, `ext3nsion-list`)
    converts(`two, one segment two extensions back slashes`, `src\\te5t-segment\\d1rectory.ext3nsion-list`, `te5tSegmentD1rectory`, `ext3nsion-list`)
    converts(`two, two segments two extensions forward slashes`, `src/te5t-segment/sub-d1rectory.ext3nsion-list`, `te5tSegmentSubD1rectory`, `ext3nsion-list`)
    converts(`two, two segments two extensions back slashes`, `src\\te5t-segment\\sub-d1rectory.ext3nsion-list`, `te5tSegmentSubD1rectory`, `ext3nsion-list`)
    converts(`two, three segments two extensions forward slashes`, `src/te5t-segment/sub-d1rectory-name.ext3nsion-list`, `te5tSegmentSubD1rectoryName`, `ext3nsion-list`)
    converts(`two, three segments two extensions back slashes`, `src\\te5t-segment\\sub-d1rectory-name.ext3nsion-list`, `te5tSegmentSubD1rectoryName`, `ext3nsion-list`)
    converts(`three, one segment two extensions forward slashes`, `src/te5t-segment-list/d1rectory.ext3nsion-list`, `te5tSegmentListD1rectory`, `ext3nsion-list`)
    converts(`three, one segment two extensions back slashes`, `src\\te5t-segment-list\\d1rectory.ext3nsion-list`, `te5tSegmentListD1rectory`, `ext3nsion-list`)
    converts(`three, two segments two extensions forward slashes`, `src/te5t-segment-list/sub-d1rectory.ext3nsion-list`, `te5tSegmentListSubD1rectory`, `ext3nsion-list`)
    converts(`three, two segments two extensions back slashes`, `src\\te5t-segment-list\\sub-d1rectory.ext3nsion-list`, `te5tSegmentListSubD1rectory`, `ext3nsion-list`)
    converts(`three, three segments two extensions forward slashes`, `src/te5t-segment-list/sub-d1rectory-name.ext3nsion-list`, `te5tSegmentListSubD1rectoryName`, `ext3nsion-list`)
    converts(`three, three segments two extensions back slashes`, `src\\te5t-segment-list\\sub-d1rectory-name.ext3nsion-list`, `te5tSegmentListSubD1rectoryName`, `ext3nsion-list`)
    converts(`one, one segment two extensions forward slashes`, `src/parent/te5t.ext3nsion-list`, `parentTe5t`, `ext3nsion-list`)
    converts(`one, one segment two extensions back slashes`, `src\\parent\\te5t.ext3nsion-list`, `parentTe5t`, `ext3nsion-list`)
    converts(`one, two segments two extensions forward slashes`, `src/parent/te5t-segment.ext3nsion-list`, `parentTe5tSegment`, `ext3nsion-list`)
    converts(`one, two segments two extensions back slashes`, `src\\parent\\te5t-segment.ext3nsion-list`, `parentTe5tSegment`, `ext3nsion-list`)
    converts(`one, three segments two extensions forward slashes`, `src/parent/te5t-segment-list.ext3nsion-list`, `parentTe5tSegmentList`, `ext3nsion-list`)
    converts(`one, three segments two extensions back slashes`, `src\\parent\\te5t-segment-list.ext3nsion-list`, `parentTe5tSegmentList`, `ext3nsion-list`)
    converts(`one, one, one segment two extensions forward slashes`, `src/parent/te5t/d1rectory.ext3nsion-list`, `parentTe5tD1rectory`, `ext3nsion-list`)
    converts(`one, one, one segment two extensions back slashes`, `src\\parent\\te5t\\d1rectory.ext3nsion-list`, `parentTe5tD1rectory`, `ext3nsion-list`)
    converts(`one, one, two segments two extensions forward slashes`, `src/parent/te5t/sub-d1rectory.ext3nsion-list`, `parentTe5tSubD1rectory`, `ext3nsion-list`)
    converts(`one, one, two segments two extensions back slashes`, `src\\parent\\te5t\\sub-d1rectory.ext3nsion-list`, `parentTe5tSubD1rectory`, `ext3nsion-list`)
    converts(`one, one, three segments two extensions forward slashes`, `src/parent/te5t/sub-d1rectory-name.ext3nsion-list`, `parentTe5tSubD1rectoryName`, `ext3nsion-list`)
    converts(`one, one, three segments two extensions back slashes`, `src\\parent\\te5t\\sub-d1rectory-name.ext3nsion-list`, `parentTe5tSubD1rectoryName`, `ext3nsion-list`)
    converts(`one, two, one segment two extensions forward slashes`, `src/parent/te5t-segment/d1rectory.ext3nsion-list`, `parentTe5tSegmentD1rectory`, `ext3nsion-list`)
    converts(`one, two, one segment two extensions back slashes`, `src\\parent\\te5t-segment\\d1rectory.ext3nsion-list`, `parentTe5tSegmentD1rectory`, `ext3nsion-list`)
    converts(`one, two, two segments two extensions forward slashes`, `src/parent/te5t-segment/sub-d1rectory.ext3nsion-list`, `parentTe5tSegmentSubD1rectory`, `ext3nsion-list`)
    converts(`one, two, two segments two extensions back slashes`, `src\\parent\\te5t-segment\\sub-d1rectory.ext3nsion-list`, `parentTe5tSegmentSubD1rectory`, `ext3nsion-list`)
    converts(`one, two, three segments two extensions forward slashes`, `src/parent/te5t-segment/sub-d1rectory-name.ext3nsion-list`, `parentTe5tSegmentSubD1rectoryName`, `ext3nsion-list`)
    converts(`one, two, three segments two extensions back slashes`, `src\\parent\\te5t-segment\\sub-d1rectory-name.ext3nsion-list`, `parentTe5tSegmentSubD1rectoryName`, `ext3nsion-list`)
    converts(`one, three, one segment two extensions forward slashes`, `src/parent/te5t-segment-list/d1rectory.ext3nsion-list`, `parentTe5tSegmentListD1rectory`, `ext3nsion-list`)
    converts(`one, three, one segment two extensions back slashes`, `src\\parent\\te5t-segment-list\\d1rectory.ext3nsion-list`, `parentTe5tSegmentListD1rectory`, `ext3nsion-list`)
    converts(`one, three, two segments two extensions forward slashes`, `src/parent/te5t-segment-list/sub-d1rectory.ext3nsion-list`, `parentTe5tSegmentListSubD1rectory`, `ext3nsion-list`)
    converts(`one, three, two segments two extensions back slashes`, `src\\parent\\te5t-segment-list\\sub-d1rectory.ext3nsion-list`, `parentTe5tSegmentListSubD1rectory`, `ext3nsion-list`)
    converts(`one, three, three segments two extensions forward slashes`, `src/parent/te5t-segment-list/sub-d1rectory-name.ext3nsion-list`, `parentTe5tSegmentListSubD1rectoryName`, `ext3nsion-list`)
    converts(`one, three, three segments two extensions back slashes`, `src\\parent\\te5t-segment-list\\sub-d1rectory-name.ext3nsion-list`, `parentTe5tSegmentListSubD1rectoryName`, `ext3nsion-list`)
    converts(`two, one segment two extensions forward slashes`, `src/parent-folder/te5t.ext3nsion-list`, `parentFolderTe5t`, `ext3nsion-list`)
    converts(`two, one segment two extensions back slashes`, `src\\parent-folder\\te5t.ext3nsion-list`, `parentFolderTe5t`, `ext3nsion-list`)
    converts(`two, two segments two extensions forward slashes`, `src/parent-folder/te5t-segment.ext3nsion-list`, `parentFolderTe5tSegment`, `ext3nsion-list`)
    converts(`two, two segments two extensions back slashes`, `src\\parent-folder\\te5t-segment.ext3nsion-list`, `parentFolderTe5tSegment`, `ext3nsion-list`)
    converts(`two, three segments two extensions forward slashes`, `src/parent-folder/te5t-segment-list.ext3nsion-list`, `parentFolderTe5tSegmentList`, `ext3nsion-list`)
    converts(`two, three segments two extensions back slashes`, `src\\parent-folder\\te5t-segment-list.ext3nsion-list`, `parentFolderTe5tSegmentList`, `ext3nsion-list`)
    converts(`two, one, one segment two extensions forward slashes`, `src/parent-folder/te5t/d1rectory.ext3nsion-list`, `parentFolderTe5tD1rectory`, `ext3nsion-list`)
    converts(`two, one, one segment two extensions back slashes`, `src\\parent-folder\\te5t\\d1rectory.ext3nsion-list`, `parentFolderTe5tD1rectory`, `ext3nsion-list`)
    converts(`two, one, two segments two extensions forward slashes`, `src/parent-folder/te5t/sub-d1rectory.ext3nsion-list`, `parentFolderTe5tSubD1rectory`, `ext3nsion-list`)
    converts(`two, one, two segments two extensions back slashes`, `src\\parent-folder\\te5t\\sub-d1rectory.ext3nsion-list`, `parentFolderTe5tSubD1rectory`, `ext3nsion-list`)
    converts(`two, one, three segments two extensions forward slashes`, `src/parent-folder/te5t/sub-d1rectory-name.ext3nsion-list`, `parentFolderTe5tSubD1rectoryName`, `ext3nsion-list`)
    converts(`two, one, three segments two extensions back slashes`, `src\\parent-folder\\te5t\\sub-d1rectory-name.ext3nsion-list`, `parentFolderTe5tSubD1rectoryName`, `ext3nsion-list`)
    converts(`two, two, one segment two extensions forward slashes`, `src/parent-folder/te5t-segment/d1rectory.ext3nsion-list`, `parentFolderTe5tSegmentD1rectory`, `ext3nsion-list`)
    converts(`two, two, one segment two extensions back slashes`, `src\\parent-folder\\te5t-segment\\d1rectory.ext3nsion-list`, `parentFolderTe5tSegmentD1rectory`, `ext3nsion-list`)
    converts(`two, two, two segments two extensions forward slashes`, `src/parent-folder/te5t-segment/sub-d1rectory.ext3nsion-list`, `parentFolderTe5tSegmentSubD1rectory`, `ext3nsion-list`)
    converts(`two, two, two segments two extensions back slashes`, `src\\parent-folder\\te5t-segment\\sub-d1rectory.ext3nsion-list`, `parentFolderTe5tSegmentSubD1rectory`, `ext3nsion-list`)
    converts(`two, two, three segments two extensions forward slashes`, `src/parent-folder/te5t-segment/sub-d1rectory-name.ext3nsion-list`, `parentFolderTe5tSegmentSubD1rectoryName`, `ext3nsion-list`)
    converts(`two, two, three segments two extensions back slashes`, `src\\parent-folder\\te5t-segment\\sub-d1rectory-name.ext3nsion-list`, `parentFolderTe5tSegmentSubD1rectoryName`, `ext3nsion-list`)
    converts(`two, three, one segment two extensions forward slashes`, `src/parent-folder/te5t-segment-list/d1rectory.ext3nsion-list`, `parentFolderTe5tSegmentListD1rectory`, `ext3nsion-list`)
    converts(`two, three, one segment two extensions back slashes`, `src\\parent-folder\\te5t-segment-list\\d1rectory.ext3nsion-list`, `parentFolderTe5tSegmentListD1rectory`, `ext3nsion-list`)
    converts(`two, three, two segments two extensions forward slashes`, `src/parent-folder/te5t-segment-list/sub-d1rectory.ext3nsion-list`, `parentFolderTe5tSegmentListSubD1rectory`, `ext3nsion-list`)
    converts(`two, three, two segments two extensions back slashes`, `src\\parent-folder\\te5t-segment-list\\sub-d1rectory.ext3nsion-list`, `parentFolderTe5tSegmentListSubD1rectory`, `ext3nsion-list`)
    converts(`two, three, three segments two extensions forward slashes`, `src/parent-folder/te5t-segment-list/sub-d1rectory-name.ext3nsion-list`, `parentFolderTe5tSegmentListSubD1rectoryName`, `ext3nsion-list`)
    converts(`two, three, three segments two extensions back slashes`, `src\\parent-folder\\te5t-segment-list\\sub-d1rectory-name.ext3nsion-list`, `parentFolderTe5tSegmentListSubD1rectoryName`, `ext3nsion-list`)
    converts(`three, one segment two extensions forward slashes`, `src/parent-folder-n0menclature/te5t.ext3nsion-list`, `parentFolderN0menclatureTe5t`, `ext3nsion-list`)
    converts(`three, one segment two extensions back slashes`, `src\\parent-folder-n0menclature\\te5t.ext3nsion-list`, `parentFolderN0menclatureTe5t`, `ext3nsion-list`)
    converts(`three, two segments two extensions forward slashes`, `src/parent-folder-n0menclature/te5t-segment.ext3nsion-list`, `parentFolderN0menclatureTe5tSegment`, `ext3nsion-list`)
    converts(`three, two segments two extensions back slashes`, `src\\parent-folder-n0menclature\\te5t-segment.ext3nsion-list`, `parentFolderN0menclatureTe5tSegment`, `ext3nsion-list`)
    converts(`three, three segments two extensions forward slashes`, `src/parent-folder-n0menclature/te5t-segment-list.ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentList`, `ext3nsion-list`)
    converts(`three, three segments two extensions back slashes`, `src\\parent-folder-n0menclature\\te5t-segment-list.ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentList`, `ext3nsion-list`)
    converts(`three, one, one segment two extensions forward slashes`, `src/parent-folder-n0menclature/te5t/d1rectory.ext3nsion-list`, `parentFolderN0menclatureTe5tD1rectory`, `ext3nsion-list`)
    converts(`three, one, one segment two extensions back slashes`, `src\\parent-folder-n0menclature\\te5t\\d1rectory.ext3nsion-list`, `parentFolderN0menclatureTe5tD1rectory`, `ext3nsion-list`)
    converts(`three, one, two segments two extensions forward slashes`, `src/parent-folder-n0menclature/te5t/sub-d1rectory.ext3nsion-list`, `parentFolderN0menclatureTe5tSubD1rectory`, `ext3nsion-list`)
    converts(`three, one, two segments two extensions back slashes`, `src\\parent-folder-n0menclature\\te5t\\sub-d1rectory.ext3nsion-list`, `parentFolderN0menclatureTe5tSubD1rectory`, `ext3nsion-list`)
    converts(`three, one, three segments two extensions forward slashes`, `src/parent-folder-n0menclature/te5t/sub-d1rectory-name.ext3nsion-list`, `parentFolderN0menclatureTe5tSubD1rectoryName`, `ext3nsion-list`)
    converts(`three, one, three segments two extensions back slashes`, `src\\parent-folder-n0menclature\\te5t\\sub-d1rectory-name.ext3nsion-list`, `parentFolderN0menclatureTe5tSubD1rectoryName`, `ext3nsion-list`)
    converts(`three, two, one segment two extensions forward slashes`, `src/parent-folder-n0menclature/te5t-segment/d1rectory.ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentD1rectory`, `ext3nsion-list`)
    converts(`three, two, one segment two extensions back slashes`, `src\\parent-folder-n0menclature\\te5t-segment\\d1rectory.ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentD1rectory`, `ext3nsion-list`)
    converts(`three, two, two segments two extensions forward slashes`, `src/parent-folder-n0menclature/te5t-segment/sub-d1rectory.ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentSubD1rectory`, `ext3nsion-list`)
    converts(`three, two, two segments two extensions back slashes`, `src\\parent-folder-n0menclature\\te5t-segment\\sub-d1rectory.ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentSubD1rectory`, `ext3nsion-list`)
    converts(`three, two, three segments two extensions forward slashes`, `src/parent-folder-n0menclature/te5t-segment/sub-d1rectory-name.ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentSubD1rectoryName`, `ext3nsion-list`)
    converts(`three, two, three segments two extensions back slashes`, `src\\parent-folder-n0menclature\\te5t-segment\\sub-d1rectory-name.ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentSubD1rectoryName`, `ext3nsion-list`)
    converts(`three, three, one segment two extensions forward slashes`, `src/parent-folder-n0menclature/te5t-segment-list/d1rectory.ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentListD1rectory`, `ext3nsion-list`)
    converts(`three, three, one segment two extensions back slashes`, `src\\parent-folder-n0menclature\\te5t-segment-list\\d1rectory.ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentListD1rectory`, `ext3nsion-list`)
    converts(`three, three, two segments two extensions forward slashes`, `src/parent-folder-n0menclature/te5t-segment-list/sub-d1rectory.ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentListSubD1rectory`, `ext3nsion-list`)
    converts(`three, three, two segments two extensions back slashes`, `src\\parent-folder-n0menclature\\te5t-segment-list\\sub-d1rectory.ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentListSubD1rectory`, `ext3nsion-list`)
    converts(`three, three, three segments two extensions forward slashes`, `src/parent-folder-n0menclature/te5t-segment-list/sub-d1rectory-name.ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentListSubD1rectoryName`, `ext3nsion-list`)
    converts(`three, three, three segments two extensions back slashes`, `src\\parent-folder-n0menclature\\te5t-segment-list\\sub-d1rectory-name.ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentListSubD1rectoryName`, `ext3nsion-list`)
    converts(`one segment three extensions forward slashes`, `src/te5t.extended-ext3nsion-list`, `te5t`, `extended-ext3nsion-list`)
    converts(`one segment three extensions back slashes`, `src\\te5t.extended-ext3nsion-list`, `te5t`, `extended-ext3nsion-list`)
    converts(`two segments three extensions forward slashes`, `src/te5t-segment.extended-ext3nsion-list`, `te5tSegment`, `extended-ext3nsion-list`)
    converts(`two segments three extensions back slashes`, `src\\te5t-segment.extended-ext3nsion-list`, `te5tSegment`, `extended-ext3nsion-list`)
    converts(`three segments three extensions forward slashes`, `src/te5t-segment-list.extended-ext3nsion-list`, `te5tSegmentList`, `extended-ext3nsion-list`)
    converts(`three segments three extensions back slashes`, `src\\te5t-segment-list.extended-ext3nsion-list`, `te5tSegmentList`, `extended-ext3nsion-list`)
    converts(`one, one segment three extensions forward slashes`, `src/te5t/d1rectory.extended-ext3nsion-list`, `te5tD1rectory`, `extended-ext3nsion-list`)
    converts(`one, one segment three extensions back slashes`, `src\\te5t\\d1rectory.extended-ext3nsion-list`, `te5tD1rectory`, `extended-ext3nsion-list`)
    converts(`one, two segments three extensions forward slashes`, `src/te5t/sub-d1rectory.extended-ext3nsion-list`, `te5tSubD1rectory`, `extended-ext3nsion-list`)
    converts(`one, two segments three extensions back slashes`, `src\\te5t\\sub-d1rectory.extended-ext3nsion-list`, `te5tSubD1rectory`, `extended-ext3nsion-list`)
    converts(`one, three segments three extensions forward slashes`, `src/te5t/sub-d1rectory-name.extended-ext3nsion-list`, `te5tSubD1rectoryName`, `extended-ext3nsion-list`)
    converts(`one, three segments three extensions back slashes`, `src\\te5t\\sub-d1rectory-name.extended-ext3nsion-list`, `te5tSubD1rectoryName`, `extended-ext3nsion-list`)
    converts(`two, one segment three extensions forward slashes`, `src/te5t-segment/d1rectory.extended-ext3nsion-list`, `te5tSegmentD1rectory`, `extended-ext3nsion-list`)
    converts(`two, one segment three extensions back slashes`, `src\\te5t-segment\\d1rectory.extended-ext3nsion-list`, `te5tSegmentD1rectory`, `extended-ext3nsion-list`)
    converts(`two, two segments three extensions forward slashes`, `src/te5t-segment/sub-d1rectory.extended-ext3nsion-list`, `te5tSegmentSubD1rectory`, `extended-ext3nsion-list`)
    converts(`two, two segments three extensions back slashes`, `src\\te5t-segment\\sub-d1rectory.extended-ext3nsion-list`, `te5tSegmentSubD1rectory`, `extended-ext3nsion-list`)
    converts(`two, three segments three extensions forward slashes`, `src/te5t-segment/sub-d1rectory-name.extended-ext3nsion-list`, `te5tSegmentSubD1rectoryName`, `extended-ext3nsion-list`)
    converts(`two, three segments three extensions back slashes`, `src\\te5t-segment\\sub-d1rectory-name.extended-ext3nsion-list`, `te5tSegmentSubD1rectoryName`, `extended-ext3nsion-list`)
    converts(`three, one segment three extensions forward slashes`, `src/te5t-segment-list/d1rectory.extended-ext3nsion-list`, `te5tSegmentListD1rectory`, `extended-ext3nsion-list`)
    converts(`three, one segment three extensions back slashes`, `src\\te5t-segment-list\\d1rectory.extended-ext3nsion-list`, `te5tSegmentListD1rectory`, `extended-ext3nsion-list`)
    converts(`three, two segments three extensions forward slashes`, `src/te5t-segment-list/sub-d1rectory.extended-ext3nsion-list`, `te5tSegmentListSubD1rectory`, `extended-ext3nsion-list`)
    converts(`three, two segments three extensions back slashes`, `src\\te5t-segment-list\\sub-d1rectory.extended-ext3nsion-list`, `te5tSegmentListSubD1rectory`, `extended-ext3nsion-list`)
    converts(`three, three segments three extensions forward slashes`, `src/te5t-segment-list/sub-d1rectory-name.extended-ext3nsion-list`, `te5tSegmentListSubD1rectoryName`, `extended-ext3nsion-list`)
    converts(`three, three segments three extensions back slashes`, `src\\te5t-segment-list\\sub-d1rectory-name.extended-ext3nsion-list`, `te5tSegmentListSubD1rectoryName`, `extended-ext3nsion-list`)
    converts(`one, one segment three extensions forward slashes`, `src/parent/te5t.extended-ext3nsion-list`, `parentTe5t`, `extended-ext3nsion-list`)
    converts(`one, one segment three extensions back slashes`, `src\\parent\\te5t.extended-ext3nsion-list`, `parentTe5t`, `extended-ext3nsion-list`)
    converts(`one, two segments three extensions forward slashes`, `src/parent/te5t-segment.extended-ext3nsion-list`, `parentTe5tSegment`, `extended-ext3nsion-list`)
    converts(`one, two segments three extensions back slashes`, `src\\parent\\te5t-segment.extended-ext3nsion-list`, `parentTe5tSegment`, `extended-ext3nsion-list`)
    converts(`one, three segments three extensions forward slashes`, `src/parent/te5t-segment-list.extended-ext3nsion-list`, `parentTe5tSegmentList`, `extended-ext3nsion-list`)
    converts(`one, three segments three extensions back slashes`, `src\\parent\\te5t-segment-list.extended-ext3nsion-list`, `parentTe5tSegmentList`, `extended-ext3nsion-list`)
    converts(`one, one, one segment three extensions forward slashes`, `src/parent/te5t/d1rectory.extended-ext3nsion-list`, `parentTe5tD1rectory`, `extended-ext3nsion-list`)
    converts(`one, one, one segment three extensions back slashes`, `src\\parent\\te5t\\d1rectory.extended-ext3nsion-list`, `parentTe5tD1rectory`, `extended-ext3nsion-list`)
    converts(`one, one, two segments three extensions forward slashes`, `src/parent/te5t/sub-d1rectory.extended-ext3nsion-list`, `parentTe5tSubD1rectory`, `extended-ext3nsion-list`)
    converts(`one, one, two segments three extensions back slashes`, `src\\parent\\te5t\\sub-d1rectory.extended-ext3nsion-list`, `parentTe5tSubD1rectory`, `extended-ext3nsion-list`)
    converts(`one, one, three segments three extensions forward slashes`, `src/parent/te5t/sub-d1rectory-name.extended-ext3nsion-list`, `parentTe5tSubD1rectoryName`, `extended-ext3nsion-list`)
    converts(`one, one, three segments three extensions back slashes`, `src\\parent\\te5t\\sub-d1rectory-name.extended-ext3nsion-list`, `parentTe5tSubD1rectoryName`, `extended-ext3nsion-list`)
    converts(`one, two, one segment three extensions forward slashes`, `src/parent/te5t-segment/d1rectory.extended-ext3nsion-list`, `parentTe5tSegmentD1rectory`, `extended-ext3nsion-list`)
    converts(`one, two, one segment three extensions back slashes`, `src\\parent\\te5t-segment\\d1rectory.extended-ext3nsion-list`, `parentTe5tSegmentD1rectory`, `extended-ext3nsion-list`)
    converts(`one, two, two segments three extensions forward slashes`, `src/parent/te5t-segment/sub-d1rectory.extended-ext3nsion-list`, `parentTe5tSegmentSubD1rectory`, `extended-ext3nsion-list`)
    converts(`one, two, two segments three extensions back slashes`, `src\\parent\\te5t-segment\\sub-d1rectory.extended-ext3nsion-list`, `parentTe5tSegmentSubD1rectory`, `extended-ext3nsion-list`)
    converts(`one, two, three segments three extensions forward slashes`, `src/parent/te5t-segment/sub-d1rectory-name.extended-ext3nsion-list`, `parentTe5tSegmentSubD1rectoryName`, `extended-ext3nsion-list`)
    converts(`one, two, three segments three extensions back slashes`, `src\\parent\\te5t-segment\\sub-d1rectory-name.extended-ext3nsion-list`, `parentTe5tSegmentSubD1rectoryName`, `extended-ext3nsion-list`)
    converts(`one, three, one segment three extensions forward slashes`, `src/parent/te5t-segment-list/d1rectory.extended-ext3nsion-list`, `parentTe5tSegmentListD1rectory`, `extended-ext3nsion-list`)
    converts(`one, three, one segment three extensions back slashes`, `src\\parent\\te5t-segment-list\\d1rectory.extended-ext3nsion-list`, `parentTe5tSegmentListD1rectory`, `extended-ext3nsion-list`)
    converts(`one, three, two segments three extensions forward slashes`, `src/parent/te5t-segment-list/sub-d1rectory.extended-ext3nsion-list`, `parentTe5tSegmentListSubD1rectory`, `extended-ext3nsion-list`)
    converts(`one, three, two segments three extensions back slashes`, `src\\parent\\te5t-segment-list\\sub-d1rectory.extended-ext3nsion-list`, `parentTe5tSegmentListSubD1rectory`, `extended-ext3nsion-list`)
    converts(`one, three, three segments three extensions forward slashes`, `src/parent/te5t-segment-list/sub-d1rectory-name.extended-ext3nsion-list`, `parentTe5tSegmentListSubD1rectoryName`, `extended-ext3nsion-list`)
    converts(`one, three, three segments three extensions back slashes`, `src\\parent\\te5t-segment-list\\sub-d1rectory-name.extended-ext3nsion-list`, `parentTe5tSegmentListSubD1rectoryName`, `extended-ext3nsion-list`)
    converts(`two, one segment three extensions forward slashes`, `src/parent-folder/te5t.extended-ext3nsion-list`, `parentFolderTe5t`, `extended-ext3nsion-list`)
    converts(`two, one segment three extensions back slashes`, `src\\parent-folder\\te5t.extended-ext3nsion-list`, `parentFolderTe5t`, `extended-ext3nsion-list`)
    converts(`two, two segments three extensions forward slashes`, `src/parent-folder/te5t-segment.extended-ext3nsion-list`, `parentFolderTe5tSegment`, `extended-ext3nsion-list`)
    converts(`two, two segments three extensions back slashes`, `src\\parent-folder\\te5t-segment.extended-ext3nsion-list`, `parentFolderTe5tSegment`, `extended-ext3nsion-list`)
    converts(`two, three segments three extensions forward slashes`, `src/parent-folder/te5t-segment-list.extended-ext3nsion-list`, `parentFolderTe5tSegmentList`, `extended-ext3nsion-list`)
    converts(`two, three segments three extensions back slashes`, `src\\parent-folder\\te5t-segment-list.extended-ext3nsion-list`, `parentFolderTe5tSegmentList`, `extended-ext3nsion-list`)
    converts(`two, one, one segment three extensions forward slashes`, `src/parent-folder/te5t/d1rectory.extended-ext3nsion-list`, `parentFolderTe5tD1rectory`, `extended-ext3nsion-list`)
    converts(`two, one, one segment three extensions back slashes`, `src\\parent-folder\\te5t\\d1rectory.extended-ext3nsion-list`, `parentFolderTe5tD1rectory`, `extended-ext3nsion-list`)
    converts(`two, one, two segments three extensions forward slashes`, `src/parent-folder/te5t/sub-d1rectory.extended-ext3nsion-list`, `parentFolderTe5tSubD1rectory`, `extended-ext3nsion-list`)
    converts(`two, one, two segments three extensions back slashes`, `src\\parent-folder\\te5t\\sub-d1rectory.extended-ext3nsion-list`, `parentFolderTe5tSubD1rectory`, `extended-ext3nsion-list`)
    converts(`two, one, three segments three extensions forward slashes`, `src/parent-folder/te5t/sub-d1rectory-name.extended-ext3nsion-list`, `parentFolderTe5tSubD1rectoryName`, `extended-ext3nsion-list`)
    converts(`two, one, three segments three extensions back slashes`, `src\\parent-folder\\te5t\\sub-d1rectory-name.extended-ext3nsion-list`, `parentFolderTe5tSubD1rectoryName`, `extended-ext3nsion-list`)
    converts(`two, two, one segment three extensions forward slashes`, `src/parent-folder/te5t-segment/d1rectory.extended-ext3nsion-list`, `parentFolderTe5tSegmentD1rectory`, `extended-ext3nsion-list`)
    converts(`two, two, one segment three extensions back slashes`, `src\\parent-folder\\te5t-segment\\d1rectory.extended-ext3nsion-list`, `parentFolderTe5tSegmentD1rectory`, `extended-ext3nsion-list`)
    converts(`two, two, two segments three extensions forward slashes`, `src/parent-folder/te5t-segment/sub-d1rectory.extended-ext3nsion-list`, `parentFolderTe5tSegmentSubD1rectory`, `extended-ext3nsion-list`)
    converts(`two, two, two segments three extensions back slashes`, `src\\parent-folder\\te5t-segment\\sub-d1rectory.extended-ext3nsion-list`, `parentFolderTe5tSegmentSubD1rectory`, `extended-ext3nsion-list`)
    converts(`two, two, three segments three extensions forward slashes`, `src/parent-folder/te5t-segment/sub-d1rectory-name.extended-ext3nsion-list`, `parentFolderTe5tSegmentSubD1rectoryName`, `extended-ext3nsion-list`)
    converts(`two, two, three segments three extensions back slashes`, `src\\parent-folder\\te5t-segment\\sub-d1rectory-name.extended-ext3nsion-list`, `parentFolderTe5tSegmentSubD1rectoryName`, `extended-ext3nsion-list`)
    converts(`two, three, one segment three extensions forward slashes`, `src/parent-folder/te5t-segment-list/d1rectory.extended-ext3nsion-list`, `parentFolderTe5tSegmentListD1rectory`, `extended-ext3nsion-list`)
    converts(`two, three, one segment three extensions back slashes`, `src\\parent-folder\\te5t-segment-list\\d1rectory.extended-ext3nsion-list`, `parentFolderTe5tSegmentListD1rectory`, `extended-ext3nsion-list`)
    converts(`two, three, two segments three extensions forward slashes`, `src/parent-folder/te5t-segment-list/sub-d1rectory.extended-ext3nsion-list`, `parentFolderTe5tSegmentListSubD1rectory`, `extended-ext3nsion-list`)
    converts(`two, three, two segments three extensions back slashes`, `src\\parent-folder\\te5t-segment-list\\sub-d1rectory.extended-ext3nsion-list`, `parentFolderTe5tSegmentListSubD1rectory`, `extended-ext3nsion-list`)
    converts(`two, three, three segments three extensions forward slashes`, `src/parent-folder/te5t-segment-list/sub-d1rectory-name.extended-ext3nsion-list`, `parentFolderTe5tSegmentListSubD1rectoryName`, `extended-ext3nsion-list`)
    converts(`two, three, three segments three extensions back slashes`, `src\\parent-folder\\te5t-segment-list\\sub-d1rectory-name.extended-ext3nsion-list`, `parentFolderTe5tSegmentListSubD1rectoryName`, `extended-ext3nsion-list`)
    converts(`three, one segment three extensions forward slashes`, `src/parent-folder-n0menclature/te5t.extended-ext3nsion-list`, `parentFolderN0menclatureTe5t`, `extended-ext3nsion-list`)
    converts(`three, one segment three extensions back slashes`, `src\\parent-folder-n0menclature\\te5t.extended-ext3nsion-list`, `parentFolderN0menclatureTe5t`, `extended-ext3nsion-list`)
    converts(`three, two segments three extensions forward slashes`, `src/parent-folder-n0menclature/te5t-segment.extended-ext3nsion-list`, `parentFolderN0menclatureTe5tSegment`, `extended-ext3nsion-list`)
    converts(`three, two segments three extensions back slashes`, `src\\parent-folder-n0menclature\\te5t-segment.extended-ext3nsion-list`, `parentFolderN0menclatureTe5tSegment`, `extended-ext3nsion-list`)
    converts(`three, three segments three extensions forward slashes`, `src/parent-folder-n0menclature/te5t-segment-list.extended-ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentList`, `extended-ext3nsion-list`)
    converts(`three, three segments three extensions back slashes`, `src\\parent-folder-n0menclature\\te5t-segment-list.extended-ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentList`, `extended-ext3nsion-list`)
    converts(`three, one, one segment three extensions forward slashes`, `src/parent-folder-n0menclature/te5t/d1rectory.extended-ext3nsion-list`, `parentFolderN0menclatureTe5tD1rectory`, `extended-ext3nsion-list`)
    converts(`three, one, one segment three extensions back slashes`, `src\\parent-folder-n0menclature\\te5t\\d1rectory.extended-ext3nsion-list`, `parentFolderN0menclatureTe5tD1rectory`, `extended-ext3nsion-list`)
    converts(`three, one, two segments three extensions forward slashes`, `src/parent-folder-n0menclature/te5t/sub-d1rectory.extended-ext3nsion-list`, `parentFolderN0menclatureTe5tSubD1rectory`, `extended-ext3nsion-list`)
    converts(`three, one, two segments three extensions back slashes`, `src\\parent-folder-n0menclature\\te5t\\sub-d1rectory.extended-ext3nsion-list`, `parentFolderN0menclatureTe5tSubD1rectory`, `extended-ext3nsion-list`)
    converts(`three, one, three segments three extensions forward slashes`, `src/parent-folder-n0menclature/te5t/sub-d1rectory-name.extended-ext3nsion-list`, `parentFolderN0menclatureTe5tSubD1rectoryName`, `extended-ext3nsion-list`)
    converts(`three, one, three segments three extensions back slashes`, `src\\parent-folder-n0menclature\\te5t\\sub-d1rectory-name.extended-ext3nsion-list`, `parentFolderN0menclatureTe5tSubD1rectoryName`, `extended-ext3nsion-list`)
    converts(`three, two, one segment three extensions forward slashes`, `src/parent-folder-n0menclature/te5t-segment/d1rectory.extended-ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentD1rectory`, `extended-ext3nsion-list`)
    converts(`three, two, one segment three extensions back slashes`, `src\\parent-folder-n0menclature\\te5t-segment\\d1rectory.extended-ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentD1rectory`, `extended-ext3nsion-list`)
    converts(`three, two, two segments three extensions forward slashes`, `src/parent-folder-n0menclature/te5t-segment/sub-d1rectory.extended-ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentSubD1rectory`, `extended-ext3nsion-list`)
    converts(`three, two, two segments three extensions back slashes`, `src\\parent-folder-n0menclature\\te5t-segment\\sub-d1rectory.extended-ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentSubD1rectory`, `extended-ext3nsion-list`)
    converts(`three, two, three segments three extensions forward slashes`, `src/parent-folder-n0menclature/te5t-segment/sub-d1rectory-name.extended-ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentSubD1rectoryName`, `extended-ext3nsion-list`)
    converts(`three, two, three segments three extensions back slashes`, `src\\parent-folder-n0menclature\\te5t-segment\\sub-d1rectory-name.extended-ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentSubD1rectoryName`, `extended-ext3nsion-list`)
    converts(`three, three, one segment three extensions forward slashes`, `src/parent-folder-n0menclature/te5t-segment-list/d1rectory.extended-ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentListD1rectory`, `extended-ext3nsion-list`)
    converts(`three, three, one segment three extensions back slashes`, `src\\parent-folder-n0menclature\\te5t-segment-list\\d1rectory.extended-ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentListD1rectory`, `extended-ext3nsion-list`)
    converts(`three, three, two segments three extensions forward slashes`, `src/parent-folder-n0menclature/te5t-segment-list/sub-d1rectory.extended-ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentListSubD1rectory`, `extended-ext3nsion-list`)
    converts(`three, three, two segments three extensions back slashes`, `src\\parent-folder-n0menclature\\te5t-segment-list\\sub-d1rectory.extended-ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentListSubD1rectory`, `extended-ext3nsion-list`)
    converts(`three, three, three segments three extensions forward slashes`, `src/parent-folder-n0menclature/te5t-segment-list/sub-d1rectory-name.extended-ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentListSubD1rectoryName`, `extended-ext3nsion-list`)
    converts(`three, three, three segments three extensions back slashes`, `src\\parent-folder-n0menclature\\te5t-segment-list\\sub-d1rectory-name.extended-ext3nsion-list`, `parentFolderN0menclatureTe5tSegmentListSubD1rectoryName`, `extended-ext3nsion-list`)

    converts(`starting a segment with a digit`, `src/big-2-can.collector`, `big2Can`, `collector`)
    converts(`starting a file name with a digit`, `src/big/2-can.collector`, `big2Can`, `collector`)
    converts(`starting a directory name with a digit`, `src/big/2-tin/can.collector`, `big2TinCan`, `collector`)
    converts(`single digit directory names`, `src/some/4/you.collector`, `some4You`, `collector`)
    converts(`single digit file names`, `src/some/4.collector`, `some4`, `collector`)

    converts(`only a $`, `src/$.collector`, `$`, `collector`)
    converts(`starting a path with a $`, `src/$tarted.collector`, `$tarted`, `collector`)
    converts(`including a $ in a path`, `src/star$ed.collector`, `star$ed`, `collector`)
    converts(`starting a segment with a $`, `src/it-$tarted.collector`, `it$tarted`, `collector`)
    converts(`including a $ in a segment`, `src/it-start$d.collector`, `itStart$d`, `collector`)
    converts(`starting a file name with a $`, `src/parent/$file.collector`, `parent$file`, `collector`)
    converts(`including a $ in a file name`, `src/parent/fi$le.collector`, `parentFi$le`, `collector`)
    converts(`a file name which is a lone $`, `src/parent/$.collector`, `parent$`, `collector`)
    converts(`starting a directory name with a $`, `src/parent/$file/end.collector`, `parent$fileEnd`, `collector`)
    converts(`including a $ in a directory name`, `src/parent/fi$le/end.collector`, `parentFi$leEnd`, `collector`)
    converts(`a directory name which is a lone $`, `src/parent/$/end.collector`, `parent$End`, `collector`)

    converts(`only an underscore`, `src/_.collector`, `_`, `collector`)
    converts(`starting a path with an underscore`, `src/_tarted.collector`, `_tarted`, `collector`)
    converts(`including an underscore in a path`, `src/star_ed.collector`, `star_ed`, `collector`)
    converts(`starting a segment with an underscore`, `src/it-_tarted.collector`, `it_tarted`, `collector`)
    converts(`including an underscore in a segment`, `src/it-start_d.collector`, `itStart_d`, `collector`)
    converts(`starting a file name with an underscore`, `src/parent/_file.collector`, `parent_file`, `collector`)
    converts(`including an underscore in a file name`, `src/parent/fi_le.collector`, `parentFi_le`, `collector`)
    converts(`a file name which is a lone underscore`, `src/parent/_.collector`, `parent_`, `collector`)
    converts(`starting a directory name with an underscore`, `src/parent/_file/end.collector`, `parent_fileEnd`, `collector`)
    converts(`including an underscore in a directory name`, `src/parent/fi_le/end.collector`, `parentFi_leEnd`, `collector`)
    converts(`a directory name which is a lone underscore`, `src/parent/_/end.collector`, `parent_End`, `collector`)

    rejects(`starting the path with a digit`, `src/2can.collector`)
    rejects(`starting the path with a hyphen`, `src/-can.collector`)
    rejects(`ending the path with a hyphen`, `src/can-.collector`)
    rejects(`double hyphens`, `src/empty--can.collector`)
    rejects(`empty extension`, `src/file.`)
    rejects(`first extension empty`, `src/file..extension`)
    rejects(`second extension empty`, `src/file.extension.`)
    rejects(`no extension`, `src/file`)
    rejects(`single digit file names without directories`, `src/4.collector`)
    rejects(`symbols at the start`, `src/%parent-folder-n0menclature/te5t-segment-list/sub-d1rectory-name.long.ext3nsion.list`)
    rejects(`symbols in the first segment`, `src/par%ent-folder-n0menclature/te5t-segment-list/sub-d1rectory-name.long.ext3nsion.list`)
    rejects(`symbols in following segments`, `src/parent-folder-n0men%clature/te5t-segment-list/sub-d1rectory-name.long.ext3nsion.list`)
    rejects(`symbols in following parts' segments`, `src/parent-folder-n0menclature/te5t-segment-li%st/sub-d1rectory-name.long.ext3nsion.list`)
    rejects(`upper case at the start`, `src/Parent-folder-n0menclature/te5t-segment-list/sub-d1rectory-name.long.ext3nsion.list`)
    rejects(`upper case in the first segment`, `src/parEnt-folder-n0menclature/te5t-segment-list/sub-d1rectory-name.long.ext3nsion.list`)
    rejects(`upper case in following segments`, `src/parent-folder-n0menClature/te5t-segment-list/sub-d1rectory-name.long.ext3nsion.list`)
    rejects(`upper case in following parts' segments`, `src/parent-folder-n0menclature/te5t-segment-liSt/sub-d1rectory-name.long.ext3nsion.list`)
  })
})
