import * as typescript from "typescript"
import { typeScriptCompilerOptions } from "./index"

describe(`@woobly/build-tool-helpers`, () => {
  describe(`typeScriptCompilerOptions`, () => {
    it(
      `exports the expected options`,
      () => expect(typeScriptCompilerOptions).toEqual({
        charset: `utf8`,
        composite: false,
        declaration: false,
        diagnostics: false,
        emitBOM: false,
        emitDeclarationOnly: false,
        incremental: false,
        inlineSourceMap: false,
        inlineSources: false,
        jsx: typescript.JsxEmit.None,
        listFiles: false,
        module: typescript.ModuleKind.None,
        newLine: typescript.NewLineKind.CarriageReturnLineFeed,
        noEmit: false,
        noEmitHelpers: false,
        noEmitOnError: true,
        noImplicitAny: true,
        noImplicitThis: true,
        noUnusedLocals: true,
        noUnusedParameters: true,
        noLib: true,
        noResolve: true,
        noStrictGenericChecks: false,
        skipDefaultLibCheck: false,
        skipLibCheck: false,
        preserveConstEnums: false,
        preserveSymlinks: false,
        preserveWatchOutput: true,
        pretty: true,
        removeComments: false,
        isolatedModules: false,
        sourceMap: false,
        suppressExcessPropertyErrors: false,
        suppressImplicitAnyIndexErrors: false,
        stripInternal: true,
        target: typescript.ScriptTarget.ES3,
        experimentalDecorators: true,
        emitDecoratorMetadata: true,
        moduleResolution: typescript.ModuleResolutionKind.Classic,
        allowUnusedLabels: false,
        noImplicitReturns: true,
        noFallthroughCasesInSwitch: true,
        allowUnreachableCode: false,
        forceConsistentCasingInFileNames: true,
        types: [],
        traceResolution: false,
        allowJs: false,
        noErrorTruncation: false,
        allowSyntheticDefaultImports: false,
        noImplicitUseStrict: true,
        listEmittedFiles: false,
        disableSizeLimit: true,
        lib: [
          `dom`
        ],
        strictNullChecks: true,
        importHelpers: false,
        alwaysStrict: true,
        strict: true,
        strictBindCallApply: true,
        downlevelIteration: true,
        strictFunctionTypes: true,
        strictPropertyInitialization: true,
        esModuleInterop: false,
        allowUmdGlobalAccess: false,
        keyofStringsOnly: true,
        declarationMap: false,
        resolveJsonModule: false,
      })
    )
  })
})
